### ISSUE TITLE
[bug] circleci notification payload .username value should use env.CIRCLE_PROJECT_USERNAME instead of env.CIRCLE_USERNAME

### ISSUE THREAD

**Issue by leojonathanoh** [theohbrothers/docker-sourceservers-beta#1]
The value of `.username` for the `circleci` notification payload should be `env.CIRCLE_PROJECT_USERNAME` instead of `env.CIRCLE_USERNAME`. This is so the value is the repository namespace, rather than the triggering user.

https://github.com/theohbrothers/docker-sourceservers-beta/blob/5b787e43e253ae3dffd97f98740377c27ee5fda3/.circleci/config.yml#L192

See circleci env vars: https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

@joeltimothyoh

**Comment by joeltimothyoh** [comment]
Good catch. Corrected. @leojonathanoh
